### ISSUE TITLE
Renaming columns doesn't persist in whole table.

### ISSUE THREAD

**Issue by NachmanBerkowitz** [e-davidson/angular-material-extensions#3]
In the table MetaData there is the option to change the column display name.  The current behavior is that in the filter picker, the column names show up as the original object keys. The expected behavior is that they would show up as they are displayed in the column headers.

**Comment by andreisrob** [comment]
[PR - use displayName instead of key in filter menu](https://github.com/e-davidson/angular-material-extensions/pull/9)

**Comment by andreisrob** [comment]
I also fixed this in the mat-card filter title, and in the Hide/Show columns menu
[Filter title](https://github.com/e-davidson/angular-material-extensions/pull/11)
[Hide/Show Columns menu](https://github.com/e-davidson/angular-material-extensions/pull/10)
