### ISSUE TITLE
add sort to state

### ISSUE THREAD

**Issue by andreisrob** [e-davidson/angular-material-extensions#45]

**Comment by e-davidson** [comment]
Should the metadata over ride what's in the store?

**Comment by andreisrob** [comment]
I think the store always wins
If it's in the same session, than it's pashut
And if I hit save after sorting, then I would think that too should be the default sort at the next session
the question is, what happens when I hit "reset"?
Are you going to wipe out the sort as well?
Go back to the ```preSort```, if defined?
Don't touch the sort at all?

**Comment by e-davidson** [comment]
done via #50
