### ISSUE TITLE
preSort direction changes when data source emits again

### ISSUE THREAD

**Issue by andreisrob** [e-davidson/angular-material-extensions#7]
Look at the following sort method: https://github.com/e-davidson/angular-material-extensions/blob/bcac0a162a24a11c19a9c469b572c3262eb6fb11/projects/table-builder/src/lib/directives/multi-sort.directive.ts#L38 It is similar to the angular source code where it runs when the user clicks a sortable column.  In that case, when the column is already active, the logical step is to sort in a different direction than the current direction.

In the directive, however, where the method runs without user interaction, every emit from the data source will run the code again, and the presorted column will change its direction since it is currently active.

To keep the direction consistent, the directive needs to run on the first emit only, but not after that.

**Comment by e-davidson** [comment]
@NachmanBerkowitz 
Can you take a look

**Comment by e-davidson** [comment]
resolved
See https://github.com/e-davidson/angular-material-extensions/commit/c1007e60f42652c6291b68bddbff6f7f9b32de3d
